const archivedTasks=[
{id:'document-delivery',title:'Document Delivery',category:'Delivery',amount:350,location:'Brgy. 176',archived:'2026-10-02',date:'Sep 29, 2026',status:'completed',statusLabel:'Completed',reason:'Completed Sep 29, 2026',rating:'5.0',desc:'Delivered documents to the requested address and confirmed receipt with the task poster.',details:'task-details-user.html?task=document-delivery',payment:'payment-record.html?task=document-delivery',review:'rate-review.html?task=document-delivery',icon:'⌂',tone:'delivery'},
{id:'weekly-market',title:'Weekly Market Run',category:'Shopping',amount:400,location:'Brgy. 179',archived:'2026-09-27',date:'Sep 22, 2026',status:'completed',statusLabel:'Completed',reason:'Completed Sep 22, 2026',rating:'4.9',desc:'Completed a weekly market shopping run and handed over all items with the receipt.',details:'task-details-user.html?task=grocery-shopping',review:'rate-review.html?task=weekly-market',icon:'🛒',tone:'shopping'},
{id:'garden-cleanup',title:'Garden Cleanup',category:'Cleaning',amount:650,location:'Brgy. 178',archived:'2026-09-18',date:'Sep 15, 2026',status:'completed',statusLabel:'Completed',reason:'Completed Sep 15, 2026',rating:'5.0',desc:'Cleared leaves, trimmed light overgrowth, and left the garden area tidy.',details:'task-details-user.html?task=garden-cleanup',review:'rate-review.html?task=garden-cleanup',icon:'🧹',tone:'cleaning'},
{id:'senior-grocery',title:'Senior Grocery Assistance',category:'Shopping',amount:550,location:'Brgy. 176',archived:'2026-09-12',date:'Sep 10, 2026',status:'completed',statusLabel:'Completed',reason:'Completed Sep 10, 2026',rating:'5.0',desc:'Picked up essential groceries and helped organize the items at the recipient’s home.',details:'task-details-user.html?task=senior-grocery',review:'rate-review.html?task=senior-grocery',icon:'🛍',tone:'shopping'},
{id:'english-tutor',title:'English Practice Session',category:'Tutoring',amount:450,location:'Brgy. 179',archived:'2026-09-04',date:'Sep 2, 2026',status:'completed',statusLabel:'Completed',reason:'Completed Sep 2, 2026',rating:'4.8',desc:'One-on-one practice focused on conversation, vocabulary, and short writing exercises.',details:'task-details-user.html?task=english-tutor',review:'rate-review.html?task=english-tutor',icon:'∑',tone:'tutoring'},
{id:'pet-walk',title:'Afternoon Pet Walk',category:'Pet Care',amount:500,location:'Brgy. 176',archived:'2026-08-29',date:'Aug 27, 2026',status:'completed',statusLabel:'Completed',reason:'Completed Aug 27, 2026',rating:'5.0',desc:'Took the family dog on a scheduled neighborhood walk and sent a completion update.',details:'task-details-user.html?task=pet-walk',review:'rate-review.html?task=pet-walk',icon:'🐾',tone:'pet'},
{id:'move-help',title:'Small Move Assistance',category:'Delivery',amount:700,location:'Brgy. 178',archived:'2026-08-22',date:'Aug 18, 2026',status:'cancelled',statusLabel:'Cancelled',reason:'Cancelled by poster before work started',desc:'The task was cancelled after the poster changed plans. No payment was recorded.',details:'task-details-user.html?task=move-help',icon:'⌂',tone:'delivery'},
{id:'math-review',title:'Math Review Session',category:'Tutoring',amount:350,location:'Brgy. 179',archived:'2026-08-15',date:'Aug 12, 2026',status:'expired',statusLabel:'Expired',reason:'Deadline passed without completion',desc:'The requested session was not completed before its scheduled deadline.',details:'task-details-user.html?task=math-review',icon:'∑',tone:'tutoring'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let filter='all';
function money(n){return '₱'+n.toLocaleString('en-PH')}
function render(){const q=($('#archiveSearch').value||'').toLowerCase().trim(),cat=$('#categoryFilter').value,sort=$('#sortArchive').value;let rows=archivedTasks.filter(t=>(filter==='all'||t.status===filter)&&(!q||`${t.title} ${t.category} ${t.location} ${t.reason}`.toLowerCase().includes(q))&&(cat==='all'||t.category===cat));rows.sort((a,b)=>sort==='highest'?b.amount-a.amount:sort==='lowest'?a.amount-b.amount:sort==='oldest'?a.archived.localeCompare(b.archived):b.archived.localeCompare(a.archived));$('#archiveList').innerHTML=rows.map(t=>`<article class="archive-card card" data-id="${t.id}"><div class="task-image ${t.tone}"><span>${t.icon}</span></div><div class="archive-main"><div class="title-row"><div><span class="status-pill ${t.status}">${t.statusLabel}</span><h2>${t.title}</h2></div><strong class="amount">${money(t.amount)}</strong></div><p>${t.desc}</p><div class="meta"><span>⚒ ${t.category}</span><span>⌖ ${t.location}</span><span>▣ ${t.reason}</span>${t.rating?`<span>★ ${t.rating} rating</span>`:''}</div><div class="actions"><a class="btn small ghost" href="${t.details}">View details</a>${t.status==='completed'?`${t.payment?`<a class="text-action" href="${t.payment}">Payment record</a>`:''}<a class="text-action" href="${t.review}">Review</a>`:''}<button class="text-action restore" data-id="${t.id}">Restore</button><button class="text-action danger remove" data-id="${t.id}">Remove</button></div></div><div class="archive-date"><small>Archived</small><strong>${new Date(t.archived+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</strong></div></article>`).join('');$('#emptyState').hidden=rows.length>0;$('#resultCount')?.remove(); $$('.restore').forEach(b=>b.onclick=()=>restore(b.dataset.id));$$('.remove').forEach(b=>b.onclick=()=>removeTask(b.dataset.id));}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2400)}
function restore(id){const t=archivedTasks.find(x=>x.id===id);if(!t)return;if(confirm(`Restore “${t.title}” to My Tasks?`)){toast(`${t.title} restored to My Tasks.`);setTimeout(()=>location.href='my-tasks.html',700)}}
function removeTask(id){const t=archivedTasks.find(x=>x.id===id);if(!t)return;if(confirm(`Remove “${t.title}” from this demo archive? This cannot be undone.`)){const i=archivedTasks.findIndex(x=>x.id===id);archivedTasks.splice(i,1);render();toast('Archived task removed from this demo view.')}}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});$('#archiveSearch').oninput=render;$('#categoryFilter').onchange=render;$('#sortArchive').onchange=render;$('#clearFilters').onclick=()=>{$('#archiveSearch').value='';$('#categoryFilter').value='all';filter='all';$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));render();toast('Filters cleared.')};
