(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const cards=$$('.user-task'), list=$('#taskList'), count=$('#resultCount'), empty=$('#emptyState'), resultsCard=document.querySelector('.results-card');
  const toast=msg=>{const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__ft);window.__ft=setTimeout(()=>el.classList.remove('show'),2200)};
  const syncBar=()=>$('#barangayFilter').value=$('#barangayQuick').value;
  function apply(){const q=($('#taskSearch').value||'').trim().toLowerCase();const cats=$$('[data-filter="category"]:checked').map(x=>x.value);const min=Number($('#minPrice').value)||0;const max=$('#maxPrice').value?Number($('#maxPrice').value):Infinity;const days=Number($('#deadlineFilter').value)||Infinity;const br=$('#barangayFilter').value;let visible=[];cards.forEach(c=>{const ok=(!q||`${c.dataset.title} ${c.dataset.category}`.toLowerCase().includes(q))&&(!cats.length||cats.includes(c.dataset.category))&&+c.dataset.price>=min&&+c.dataset.price<=max&&+c.dataset.days<=days&&(br==='all'||c.dataset.barangay===br);c.hidden=!ok;if(ok)visible.push(c)});const sort=$('#sortTasks').value;visible.sort((a,b)=>sort==='price-low'?+a.dataset.price-+b.dataset.price:sort==='price-high'?+b.dataset.price-+a.dataset.price:sort==='deadline'?+a.dataset.days-+b.dataset.days:0);visible.forEach(c=>list.appendChild(c));count.textContent=visible.length;empty.hidden=visible.length>0;resultsCard?.classList.toggle('empty',!visible.length);const nearby=$('#nearbyOnly').checked;if(nearby&&br==='all')toast('Select a barangay to use Nearby only.');}
  $('#searchBtn')?.addEventListener('click',apply); $('#taskSearch')?.addEventListener('input',apply); $('#sortTasks')?.addEventListener('change',apply); $('#barangayQuick')?.addEventListener('change',()=>{syncBar();apply()}); $('#barangayFilter')?.addEventListener('change',()=>{const v=$('#barangayFilter').value;$('#barangayQuick').value=v;apply()}); $('#applyFilters')?.addEventListener('click',()=>{apply();toast('Filters applied.')});
  $('#resetFilters')?.addEventListener('click',()=>{ $$('[data-filter="category"]').forEach(x=>x.checked=false);$('#minPrice').value='';$('#maxPrice').value='';$('#deadlineFilter').value='all';$('#barangayFilter').value='all';$('#barangayQuick').value='all';$('#nearbyOnly').checked=false;$('#taskSearch').value='';apply();toast('Filters reset.')}); $('#emptyReset')?.addEventListener('click',()=>$('#resetFilters').click());
  $('#filterToggle')?.addEventListener('click',()=>$('#filtersPanel')?.classList.toggle('open'));
  $$('.save').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();btn.classList.toggle('saved');btn.textContent=btn.classList.contains('saved')?'♥':'♡';toast(btn.classList.contains('saved')?'Task saved.':'Task removed from saved tasks.')}));
  $$('.view-switch button').forEach(b=>b.addEventListener('click',()=>{$$('.view-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');resultsCard?.classList.toggle('map-mode',b.dataset.view==='map')}));
  $$('.map-pin').forEach(pin=>pin.addEventListener('click',()=>{$$('.map-pin').forEach(p=>p.classList.remove('active'));pin.classList.add('active');const card=cards.find(c=>c.dataset.pin===pin.dataset.pin);cards.forEach(c=>c.classList.remove('selected'));card?.classList.add('selected');card?.scrollIntoView({block:'nearest'})}));
  cards.forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;$$('.user-task').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');const pin=$(`.map-pin[data-pin="${card.dataset.pin}"]`);$$('.map-pin').forEach(p=>p.classList.remove('active'));pin?.classList.add('active')}));
  let zoom=1;const canvas=$('.map-canvas');$('#zoomIn')?.addEventListener('click',()=>{zoom=Math.min(1.35,zoom+.1);canvas.style.transform=`scale(${zoom})`;canvas.style.transformOrigin='center'});$('#zoomOut')?.addEventListener('click',()=>{zoom=Math.max(1,zoom-.1);canvas.style.transform=`scale(${zoom})`;canvas.style.transformOrigin='center'});
  apply();
})();
