const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=(m)=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),2600)};
const modal=$('#modalBackdrop'),body=$('#modalBody');
function openModal(html){body.innerHTML=html;modal.classList.add('show');}
function closeModal(){modal.classList.remove('show');body.innerHTML='';}
$('#modalClose')?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function message(){openModal(`<h2>Message Angela</h2><p>Start a task-focused conversation. Keep personal and financial information private until it is genuinely needed.</p><div class="field"><label for="msgText">Your message</label><textarea id="msgText" placeholder="Hi Angela, I’m interested in working with you on a task..."></textarea></div><div class="modal-actions"><button class="btn ghost" id="cancelModal">Cancel</button><button class="btn primary" id="sendMsg">Open conversation</button></div>`);$('#cancelModal').onclick=closeModal;$('#sendMsg').onclick=()=>{const v=$('#msgText').value.trim();if(!v){$('#msgText').focus();return}closeModal();toast('Conversation opened with Angela');setTimeout(()=>location.href='messages.html?conversation=angela',500)};}
$('#messageBtn')?.addEventListener('click',message);$('#messageBtnSide')?.addEventListener('click',message);
$('#shareBtn')?.addEventListener('click',()=>{openModal(`<h2>Share Angela’s profile</h2><p>You can share this public profile with someone who needs a trusted local task doer.</p><div class="share-box">TaskTap public profile · Angela M. Cruz</div><div class="modal-actions"><button class="btn ghost" id="closeShare">Close</button><button class="btn primary" id="copyShare">Copy profile link</button></div>`);$('#closeShare').onclick=closeModal;$('#copyShare').onclick=()=>{navigator.clipboard?.writeText(location.href).catch(()=>{});closeModal();toast('Profile link copied');};});
$('#reviewsBtn')?.addEventListener('click',()=>toast('Showing the latest public reviews in this demo'));
$('#reportBtn')?.addEventListener('click',()=>{openModal(`<h2>Report profile</h2><p>Choose a reason. This demo does not submit a real moderation report.</p><div class="field"><label for="reportReason">Reason</label><select id="reportReason"><option>Suspicious or misleading profile</option><option>Harassment or unsafe behavior</option><option>Spam or inappropriate content</option><option>Other</option></select></div><div class="field"><label for="reportNote">Additional details</label><textarea id="reportNote" placeholder="Optional details..."></textarea></div><div class="modal-actions"><button class="btn ghost" id="cancelReport">Cancel</button><button class="btn primary" id="submitReport">Submit report</button></div>`);$('#cancelReport').onclick=closeModal;$('#submitReport').onclick=()=>{closeModal();toast('Demo report recorded');};});
