const received=[
 {name:'Maria Santos',initials:'MS',rating:5,date:'Oct 1, 2026',task:'House Cleaning',text:'Joshua was punctual, careful with the task, and easy to coordinate with. Would definitely work with him again.',type:'received'},
 {name:'Juan Reyes',initials:'JR',rating:5,date:'Sep 26, 2026',task:'Fix a leaking faucet',text:'Great communication and the repair was completed exactly as discussed.',type:'received'},
 {name:'Ana Cruz',initials:'AC',rating:5,date:'Sep 18, 2026',task:'Grocery Shopping',text:'Very reliable and thoughtful. Joshua followed the list, kept the receipts, and gave clear updates.',type:'received'},
 {name:'Carlo Mendoza',initials:'CM',rating:4,date:'Sep 12, 2026',task:'Document Delivery',text:'Good experience overall. Communication was clear and the delivery was completed on time.',type:'received'},
 {name:'Liza Garcia',initials:'LG',rating:5,date:'Sep 5, 2026',task:'Pet Care',text:'Friendly, careful, and dependable. My instructions were followed exactly.',type:'received'},
 {name:'Ramon Dela Cruz',initials:'RD',rating:5,date:'Aug 28, 2026',task:'Apartment Cleaning',text:'Excellent work and very easy to coordinate with. The space was left neat and organized.',type:'received'}
];
const given=[
 {name:'Angela Reyes',initials:'AR',rating:5,date:'Oct 2, 2026',task:'Math Tutor (Grade 10)',text:'Angela explained the topics clearly and was patient throughout the session.',type:'given'},
 {name:'Mark Villanueva',initials:'MV',rating:5,date:'Sep 29, 2026',task:'Document Delivery',text:'Mark was responsive, professional, and confirmed delivery promptly.',type:'given'},
 {name:'Bea Ramos',initials:'BR',rating:4,date:'Sep 21, 2026',task:'Pet Care',text:'Friendly and attentive. A little more communication during the task would have made it excellent.',type:'given'},
 {name:'Paolo Santos',initials:'PS',rating:5,date:'Sep 14, 2026',task:'Basic Computer Help',text:'Solved the issue quickly and explained the steps in a way that was easy to follow.',type:'given'}
];
let active='received';let data=received;
const $=s=>document.querySelector(s);const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function render(){const q=$('#reviewSearch').value.trim().toLowerCase(),rf=$('#ratingFilter').value,sort=$('#sortReviews').value;let rows=data.filter(r=>(!q||`${r.name} ${r.task} ${r.text}`.toLowerCase().includes(q))&&(rf==='all'||String(r.rating)===rf));rows.sort((a,b)=>{if(sort==='highest')return b.rating-a.rating;if(sort==='lowest')return a.rating-b.rating;return sort==='oldest'?new Date(a.date)-new Date(b.date):new Date(b.date)-new Date(a.date)});$('#reviewList').innerHTML=rows.map(r=>`<article class="review-card card ${r.type==='given'?'given-card':''}"><div class="review-card-head"><div class="review-person"><div class="review-avatar">${r.initials}</div><div><strong>${esc(r.name)}</strong><small>${r.type==='received'?'Reviewed you':'You reviewed this member'}</small></div></div><div class="review-rating"><div class="stars">${'★'.repeat(r.rating)}<span style="color:#d7dee7">${'★'.repeat(5-r.rating)}</span></div><time>${r.date}</time></div></div><p class="review-body">${esc(r.text)}</p><div class="review-task"><span>Task · <strong>${esc(r.task)}</strong></span><a href="${r.type==='received'?'public-profile.html?user='+encodeURIComponent(r.name):'task-details-user.html?task=completed'}">${r.type==='received'?'View profile':'View task'} →</a></div>${r.type==='received'&&r.rating===5?'<div class="reply"><strong>Great feedback:</strong> Your review helps other members understand what working with you is like.</div>':''}</article>`).join('');$('#emptyState').hidden=rows.length>0}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');active=btn.dataset.tab;data=active==='received'?received:given;$('#ratingFilter').value='all';render()}));
['reviewSearch','ratingFilter','sortReviews'].forEach(id=>$( '#'+id).addEventListener('input',render));$('#clearFilters').addEventListener('click',()=>{$('#reviewSearch').value='';$('#ratingFilter').value='all';$('#sortReviews').value='newest';render();toast('Filters cleared.')});render();
